force-app/main/default/objects/AccountRole__c/AccountRole__c.object-meta.xml
<CustomObject>
    <label>AccountRole</label>
    <nameField>
        <label>Account_Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountRoles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountRole__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountName</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountRoles</relationshipLabel>
    <relationshipName>AccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountRole__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AccountRoles</relationshipLabel>
    <relationshipName>AccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountRole__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**
    *Name:- TestDataFactory class
	*Desc:- this is a class where we create Test data for Test Classes
**/
public class TestDataFactory {
    
    /**
    *Name	:- createBulkAccount()
	@Params	:- Integer numOfCount (Total Number of Counts)
	@return :- List<Account> (return the List of Accounts)
	*Desc	:- this function is used to create Bulk Account records
	**/
	public static Account createAccount(Integer num){
        Account Acc = new Account(Name = 'TestAccount'+num);
        
		// Return acclist
        return Acc;
    } // End createAccount()
    
    /**
    *Name	:- createBulkContact()
	@Params	:- List<Account> accList (List of Accounts) And Integer numOfCount (Total Number of Counts)
	@Return :- List<Contact> (return the List of Contacts)
	*Desc	:- this function is used to create 4 contacts for Each Account Records
	**/
	public static Contact createBulkContact(Id accId, Integer num,Integer Amount){
        
		Contact con = new Contact(LastName = 'Contact'+num, AccountId = accId, Amount__c= Amount);
        // Return conList
         return con;
     
    } // End createBulkContact()
    
    /**
    *Name	:- createBulkAccountRole()
	@Params	:- List<Account> accList (List of Accounts Associated with Contacts) And Integer numOfCount (Total Number of Counts)
	@Return :- List<AccountRole__c> (return the List of AccountRoles)
	*Desc	:- this function is used to create 2 AccountRoles for Each Account Records
	**/
    public static AccountRole__c createBulkAccountRole(Id accId,Id conId, Integer num, String roleVal){
        
       AccountRole__c accRole = new AccountRole__c(Name = 'AccountRole'+num, Role__c = roleVal,
                                                                 Contact__c = conId, AccountId__c = accId );

        //Return accRoleList
        return accRole;
        
    } // End createBulkAccountRole()

} // End AccountRoleTestData_Factory